sonar.projectKey=Enterprisegit
sonar.projectName=Enterprisegit
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9001
sonar.login=sqp_bd66d27f1ede0b48d8d1a8735d6b2c719b7aa36d